# fly.toml app configuration file generated for mmb on 2023-07-24T13:42:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mmb"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
